# `before-compose` is created as a reference
# because the path will be changed when using docker compose

# ! Please make sure you are in root directory before running this file

FROM node:12.18.1 

# set up image working directory. and this is best practice
# https://stackoverflow.com/questions/51066146/what-is-the-point-of-workdir-on-dockerfile
WORKDIR /app

# copy files from current directory to docker image
COPY ./2-database-and-compose/package.json package.json
COPY ./2-database-and-compose/package-lock.json package-lock.json

RUN npm install

COPY ./2-database-and-compose/server.js .

CMD ["node","server.js"]